### ISSUE TITLE
Amend Deprecation Notice

### ISSUE THREAD

**Issue by lorenzleutgeb** [palantir/eslint-config-palantir#5]
I am reading on the net on how to migrate from TSLint to ESLint.

My main sources of information are:
 1. ["TSLint in 2019" (medium.com/palantir,  2019-02-19)](https://medium.com/palantir/tslint-in-2019-1a144c2317a9)
 1. ["The future of TypeScript on ESLint" (eslint.org)](https://eslint.org/blog/2019/01/future-typescript-eslint)

I noted that (1.) refers to something called `eslint-config-palantir` which I believe is the code in this repo:

> Once the ESLint static analysis checks are on a par with TSLint, we’ll publish an `eslint-config-palantir` package, a drop-in ESLint replacement for our TSLint rule set.

If this is true, then I believe that you should change your `README.md` to reflect that this package's hiatus will end at some point. Currently it reads as if there's no way back and this package will never be updated again.

For users that plan to use Palantir's ruleset with ESLint, this package would be valuable. Maybe it is even worth mentioning in the miration docs being discussed at typescript-eslint/typescript-eslint#36.

**Comment by adidahiya** [comment]
yeah, good call. I'll update this repo's messaging

**Comment by lorenzleutgeb** [comment]
![tumbleweed](https://media.giphy.com/media/Az1CJ2MEjmsp2/giphy.gif)
